### ISSUE TITLE
java project auto deployment (to wowza)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dlss-wowza#2]
the capistrano equivalent to get correct java artifacts to correct spot on wowza server(s) for deployment.
- [x] which jars or other artifacts need to be built for deployment
  - [x] which wowza jars need to be included in deployment
- [x] how to deploy them, and how (e.g. github release files? part of deploy scripts? how version them? etc.)

Also application.xml file.

Gradle is currently the preferred tool for builds / running tests (it's already in place and used by travis), though developing Eclipse Wowza plugins with the eclipse plugins gives us an ant build.xml file to build the jar ...  (Naomi has tweaked her local task to keep out test classes)

**Comment by tingulfsen** [comment]
I think that auto deployment should probably include an application definition. By this I mean the Application.xml file that defines a Wowza "application". I suppose you could keep Application.xml separate from this Java codebase, but it would be ideal to automatically deploy this file when we deploy the code.

**Comment by ndushay** [comment]
I agree.  I was just thinking about this this morning!

**Comment by ndushay** [comment]
Consider whether Application.xml should be in puppet.

**Comment by ndushay** [comment]
I'm beginning to think we should just use capistrano with customized deploy tasks.  It speaks git repo, and it can execute commands remotely and we have the one-time-key stuff for ssh to remote boxes ...

http://rockyj.in/2012/09/01/deploying_java_apps_with_capistrano.html

**Comment by ndushay** [comment]
or maybe this gradle plugin:   https://gradle-ssh-plugin.github.io/

**Comment by jmartin-sul** [comment]
discussed briefly with @eefahy this afternoon, and it turns out we already have a sort of standard approach for java project deployments:  use jenkins.  it can use an event such as merging to master as a trigger, and then it can build an artifact (such as a jar file), and put it in a known place (e.g. a lib directory full of wowza plugins).  erin says it might involve a bit more puppet than usual.  `Application.xml` deployment should also be feasible.

erin said we can discuss in more detail tomorrow.  seems like it'd be good to @ndushay there, if possible.

i explored the gradle ssh plugin, and ran into trouble because it doesn't seem to do kerb authentication.  i filed int128/groovy-ssh#141 with the underlying groovy-ssh library that the plugin uses (they both appear to have the same maintainer).  though if we go with jenkins for deployment, that'll be a moot point for us.

also likely moot if jenkins works out for us, but capturing it here for posterity's sake:  while i totally agree that the consistency with other projects is a nice advantage of capistrano, i was somewhat hesitant to mix ruby into this project, since there's also some cognitive overhead to having multiple languages used in a project.  e.g. adding capistrano would mean that there'd be a `config` directory in addition to the existing `conf` directory, plus the wierd-at-first-glance sight of `Gemfile` alongside `build.gradle`.  also, the cap documentation's not the best, and i found it to be a hassle the one time i had to setup a cap deployment for something that wasn't a vanilla rails app (not sure if a non-ruby app would be easier or harder than a non-standard rails app).

anyway, fingers crossed that jenkins is the answer to this problem.

**Comment by jmartin-sul** [comment]
a couple of small updates:
- we won't be deploying Application.xml.  instructions for Application.xml settings are in the plugin README.
- we're merging a version of this functionality that works well enough, but have filed issue #23 for more robust build functionality.

**Comment by jmartin-sul** [comment]
a SAR ticket has been filed for the puppet part, so closing this issue for now.  will reopen if that doesn't work out.
